// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.6
// source: lobby/lobby.proto

package lobby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LobbyMembership int32

const (
	LobbyMembership_LOBBY_MEMBERSHIP_UNKNOWN LobbyMembership = 0
	LobbyMembership_LOBBY_MEMBERSHIP_OWNER   LobbyMembership = 1
	LobbyMembership_LOBBY_MEMBERSHIP_GUEST   LobbyMembership = 2
)

// Enum value maps for LobbyMembership.
var (
	LobbyMembership_name = map[int32]string{
		0: "LOBBY_MEMBERSHIP_UNKNOWN",
		1: "LOBBY_MEMBERSHIP_OWNER",
		2: "LOBBY_MEMBERSHIP_GUEST",
	}
	LobbyMembership_value = map[string]int32{
		"LOBBY_MEMBERSHIP_UNKNOWN": 0,
		"LOBBY_MEMBERSHIP_OWNER":   1,
		"LOBBY_MEMBERSHIP_GUEST":   2,
	}
)

func (x LobbyMembership) Enum() *LobbyMembership {
	p := new(LobbyMembership)
	*p = x
	return p
}

func (x LobbyMembership) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LobbyMembership) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_lobby_proto_enumTypes[0].Descriptor()
}

func (LobbyMembership) Type() protoreflect.EnumType {
	return &file_lobby_lobby_proto_enumTypes[0]
}

func (x LobbyMembership) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LobbyMembership.Descriptor instead.
func (LobbyMembership) EnumDescriptor() ([]byte, []int) {
	return file_lobby_lobby_proto_rawDescGZIP(), []int{0}
}

type Lobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Members  []*LobbyMember `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Settings *LobbySettings `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`
}

func (x *Lobby) Reset() {
	*x = Lobby{}
	mi := &file_lobby_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lobby) ProtoMessage() {}

func (x *Lobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lobby.ProtoReflect.Descriptor instead.
func (*Lobby) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *Lobby) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lobby) GetMembers() []*LobbyMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Lobby) GetSettings() *LobbySettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type LobbyMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerNickname string          `protobuf:"bytes,1,opt,name=playerNickname,proto3" json:"playerNickname,omitempty"`
	Membership     LobbyMembership `protobuf:"varint,2,opt,name=membership,proto3,enum=lobby.LobbyMembership" json:"membership,omitempty"`
}

func (x *LobbyMember) Reset() {
	*x = LobbyMember{}
	mi := &file_lobby_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyMember) ProtoMessage() {}

func (x *LobbyMember) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyMember.ProtoReflect.Descriptor instead.
func (*LobbyMember) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *LobbyMember) GetPlayerNickname() string {
	if x != nil {
		return x.PlayerNickname
	}
	return ""
}

func (x *LobbyMember) GetMembership() LobbyMembership {
	if x != nil {
		return x.Membership
	}
	return LobbyMembership_LOBBY_MEMBERSHIP_UNKNOWN
}

type LobbySettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerCapacity        int32 `protobuf:"varint,1,opt,name=playerCapacity,proto3" json:"playerCapacity,omitempty"`
	GameDurationInSeconds int32 `protobuf:"varint,2,opt,name=gameDurationInSeconds,proto3" json:"gameDurationInSeconds,omitempty"`
}

func (x *LobbySettings) Reset() {
	*x = LobbySettings{}
	mi := &file_lobby_lobby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbySettings) ProtoMessage() {}

func (x *LobbySettings) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbySettings.ProtoReflect.Descriptor instead.
func (*LobbySettings) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *LobbySettings) GetPlayerCapacity() int32 {
	if x != nil {
		return x.PlayerCapacity
	}
	return 0
}

func (x *LobbySettings) GetGameDurationInSeconds() int32 {
	if x != nil {
		return x.GameDurationInSeconds
	}
	return 0
}

var File_lobby_lobby_proto protoreflect.FileDescriptor

var file_lobby_lobby_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x22, 0x77, 0x0a, 0x05, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4c, 0x6f, 0x62,
	0x62, 0x79, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x12, 0x30, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x22, 0x6d, 0x0a, 0x0b, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16,
	0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x22, 0x6d, 0x0a, 0x0d, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x61, 0x70,
	0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x34, 0x0a, 0x15, 0x67,
	0x61, 0x6d, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x67, 0x61, 0x6d, 0x65,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x2a, 0x67, 0x0a, 0x0f, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x12, 0x1c, 0x0a, 0x18, 0x4c, 0x4f, 0x42, 0x42, 0x59, 0x5f, 0x4d, 0x45,
	0x4d, 0x42, 0x45, 0x52, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x4c, 0x4f, 0x42, 0x42, 0x59, 0x5f, 0x4d, 0x45, 0x4d, 0x42,
	0x45, 0x52, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x4f, 0x57, 0x4e, 0x45, 0x52, 0x10, 0x01, 0x12, 0x1a,
	0x0a, 0x16, 0x4c, 0x4f, 0x42, 0x42, 0x59, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x53, 0x48,
	0x49, 0x50, 0x5f, 0x47, 0x55, 0x45, 0x53, 0x54, 0x10, 0x02, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x69, 0x6b, 0x6f, 0x6e, 0x65,
	0x4b, 0x69, 0x73, 0x75, 0x2f, 0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2d, 0x69, 0x74, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lobby_lobby_proto_rawDescOnce sync.Once
	file_lobby_lobby_proto_rawDescData = file_lobby_lobby_proto_rawDesc
)

func file_lobby_lobby_proto_rawDescGZIP() []byte {
	file_lobby_lobby_proto_rawDescOnce.Do(func() {
		file_lobby_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(file_lobby_lobby_proto_rawDescData)
	})
	return file_lobby_lobby_proto_rawDescData
}

var file_lobby_lobby_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lobby_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lobby_lobby_proto_goTypes = []any{
	(LobbyMembership)(0),  // 0: lobby.LobbyMembership
	(*Lobby)(nil),         // 1: lobby.Lobby
	(*LobbyMember)(nil),   // 2: lobby.LobbyMember
	(*LobbySettings)(nil), // 3: lobby.LobbySettings
}
var file_lobby_lobby_proto_depIdxs = []int32{
	2, // 0: lobby.Lobby.members:type_name -> lobby.LobbyMember
	3, // 1: lobby.Lobby.settings:type_name -> lobby.LobbySettings
	0, // 2: lobby.LobbyMember.membership:type_name -> lobby.LobbyMembership
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_lobby_lobby_proto_init() }
func file_lobby_lobby_proto_init() {
	if File_lobby_lobby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lobby_lobby_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lobby_lobby_proto_goTypes,
		DependencyIndexes: file_lobby_lobby_proto_depIdxs,
		EnumInfos:         file_lobby_lobby_proto_enumTypes,
		MessageInfos:      file_lobby_lobby_proto_msgTypes,
	}.Build()
	File_lobby_lobby_proto = out.File
	file_lobby_lobby_proto_rawDesc = nil
	file_lobby_lobby_proto_goTypes = nil
	file_lobby_lobby_proto_depIdxs = nil
}
