// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.6
// source: lobby/lobby-controller.proto

package lobby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata: auth-token
type CreateLobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbySettings *LobbySettings `protobuf:"bytes,1,opt,name=lobbySettings,proto3" json:"lobbySettings,omitempty"`
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	mi := &file_lobby_lobby_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_controller_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLobbyRequest) GetLobbySettings() *LobbySettings {
	if x != nil {
		return x.LobbySettings
	}
	return nil
}

type CreateLobbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lobby          *Lobby `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	HasGameStarted bool   `protobuf:"varint,2,opt,name=hasGameStarted,proto3" json:"hasGameStarted,omitempty"`
}

func (x *CreateLobbyResponse) Reset() {
	*x = CreateLobbyResponse{}
	mi := &file_lobby_lobby_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyResponse) ProtoMessage() {}

func (x *CreateLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyResponse.ProtoReflect.Descriptor instead.
func (*CreateLobbyResponse) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_controller_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLobbyResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

func (x *CreateLobbyResponse) GetHasGameStarted() bool {
	if x != nil {
		return x.HasGameStarted
	}
	return false
}

// metadata: auth-token
type JoinLobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyId string `protobuf:"bytes,1,opt,name=lobbyId,proto3" json:"lobbyId,omitempty"`
}

func (x *JoinLobbyRequest) Reset() {
	*x = JoinLobbyRequest{}
	mi := &file_lobby_lobby_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyRequest) ProtoMessage() {}

func (x *JoinLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyRequest.ProtoReflect.Descriptor instead.
func (*JoinLobbyRequest) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_controller_proto_rawDescGZIP(), []int{2}
}

func (x *JoinLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

type JoinLobbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lobby          *Lobby `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	HasGameStarted bool   `protobuf:"varint,2,opt,name=hasGameStarted,proto3" json:"hasGameStarted,omitempty"`
}

func (x *JoinLobbyResponse) Reset() {
	*x = JoinLobbyResponse{}
	mi := &file_lobby_lobby_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyResponse) ProtoMessage() {}

func (x *JoinLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyResponse.ProtoReflect.Descriptor instead.
func (*JoinLobbyResponse) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_controller_proto_rawDescGZIP(), []int{3}
}

func (x *JoinLobbyResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

func (x *JoinLobbyResponse) GetHasGameStarted() bool {
	if x != nil {
		return x.HasGameStarted
	}
	return false
}

// metadata: auth-token
type LeaveMyLobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaveMyLobbyRequest) Reset() {
	*x = LeaveMyLobbyRequest{}
	mi := &file_lobby_lobby_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveMyLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveMyLobbyRequest) ProtoMessage() {}

func (x *LeaveMyLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveMyLobbyRequest.ProtoReflect.Descriptor instead.
func (*LeaveMyLobbyRequest) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_controller_proto_rawDescGZIP(), []int{4}
}

type LeaveMyLobbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaveMyLobbyResponse) Reset() {
	*x = LeaveMyLobbyResponse{}
	mi := &file_lobby_lobby_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveMyLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveMyLobbyResponse) ProtoMessage() {}

func (x *LeaveMyLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveMyLobbyResponse.ProtoReflect.Descriptor instead.
func (*LeaveMyLobbyResponse) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_controller_proto_rawDescGZIP(), []int{5}
}

type GetLobbiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page         int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	ItemsPerPage int32 `protobuf:"varint,2,opt,name=itemsPerPage,proto3" json:"itemsPerPage,omitempty"`
}

func (x *GetLobbiesRequest) Reset() {
	*x = GetLobbiesRequest{}
	mi := &file_lobby_lobby_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLobbiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLobbiesRequest) ProtoMessage() {}

func (x *GetLobbiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLobbiesRequest.ProtoReflect.Descriptor instead.
func (*GetLobbiesRequest) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_controller_proto_rawDescGZIP(), []int{6}
}

func (x *GetLobbiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLobbiesRequest) GetItemsPerPage() int32 {
	if x != nil {
		return x.ItemsPerPage
	}
	return 0
}

type GetLobbiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page         int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	ItemsPerPage int32    `protobuf:"varint,2,opt,name=itemsPerPage,proto3" json:"itemsPerPage,omitempty"`
	TotalPages   int32    `protobuf:"varint,3,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	TotalItems   int32    `protobuf:"varint,4,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	Items        []*Lobby `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetLobbiesResponse) Reset() {
	*x = GetLobbiesResponse{}
	mi := &file_lobby_lobby_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLobbiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLobbiesResponse) ProtoMessage() {}

func (x *GetLobbiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLobbiesResponse.ProtoReflect.Descriptor instead.
func (*GetLobbiesResponse) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_controller_proto_rawDescGZIP(), []int{7}
}

func (x *GetLobbiesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLobbiesResponse) GetItemsPerPage() int32 {
	if x != nil {
		return x.ItemsPerPage
	}
	return 0
}

func (x *GetLobbiesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetLobbiesResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *GetLobbiesResponse) GetItems() []*Lobby {
	if x != nil {
		return x.Items
	}
	return nil
}

// metadata: auth-token
type CloseLobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseLobbyRequest) Reset() {
	*x = CloseLobbyRequest{}
	mi := &file_lobby_lobby_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseLobbyRequest) ProtoMessage() {}

func (x *CloseLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseLobbyRequest.ProtoReflect.Descriptor instead.
func (*CloseLobbyRequest) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_controller_proto_rawDescGZIP(), []int{8}
}

type CloseLobbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseLobbyResponse) Reset() {
	*x = CloseLobbyResponse{}
	mi := &file_lobby_lobby_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseLobbyResponse) ProtoMessage() {}

func (x *CloseLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseLobbyResponse.ProtoReflect.Descriptor instead.
func (*CloseLobbyResponse) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_controller_proto_rawDescGZIP(), []int{9}
}

var File_lobby_lobby_controller_proto protoreflect.FileDescriptor

var file_lobby_lobby_controller_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2d, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x1a, 0x11, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2f, 0x6c, 0x6f, 0x62,
	0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a,
	0x0a, 0x0d, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x0d, 0x6c, 0x6f, 0x62,
	0x62, 0x79, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x61, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x22, 0x0a, 0x05, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x05,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x68, 0x61, 0x73, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x68,
	0x61, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x22, 0x2c, 0x0a,
	0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x11, 0x4a,
	0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x05, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x05, 0x6c,
	0x6f, 0x62, 0x62, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x68, 0x61, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x68, 0x61,
	0x73, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x22, 0x15, 0x0a, 0x13,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x4d, 0x79, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x4d, 0x79, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4b, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x4c, 0x6f, 0x62, 0x62, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x50, 0x65, 0x72,
	0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x50, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x22, 0xb0, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x4c, 0x6f, 0x62, 0x62, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x50, 0x65, 0x72, 0x50,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x50, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x50, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4c,
	0x6f, 0x62, 0x62, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x14, 0x0a, 0x12, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xec, 0x02, 0x0a, 0x0f, 0x4c, 0x6f, 0x62, 0x62, 0x79,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x19, 0x2e, 0x6c, 0x6f, 0x62, 0x62,
	0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x30, 0x01, 0x12, 0x40, 0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12,
	0x17, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79,
	0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x30, 0x01, 0x12, 0x47, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x4d, 0x79, 0x4c,
	0x6f, 0x62, 0x62, 0x79, 0x12, 0x1a, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x4d, 0x79, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x4d, 0x79,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x62, 0x62, 0x69, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x6c, 0x6f,
	0x62, 0x62, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x62, 0x62, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x47, 0x65,
	0x74, 0x4c, 0x6f, 0x62, 0x62, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x43, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4d, 0x79, 0x4c, 0x6f, 0x62, 0x62, 0x79,
	0x12, 0x18, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x6f, 0x62,
	0x62, 0x79, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x69, 0x6b, 0x6f, 0x6e, 0x65, 0x4b, 0x69, 0x73, 0x75, 0x2f,
	0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2d, 0x69, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lobby_lobby_controller_proto_rawDescOnce sync.Once
	file_lobby_lobby_controller_proto_rawDescData = file_lobby_lobby_controller_proto_rawDesc
)

func file_lobby_lobby_controller_proto_rawDescGZIP() []byte {
	file_lobby_lobby_controller_proto_rawDescOnce.Do(func() {
		file_lobby_lobby_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_lobby_lobby_controller_proto_rawDescData)
	})
	return file_lobby_lobby_controller_proto_rawDescData
}

var file_lobby_lobby_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_lobby_lobby_controller_proto_goTypes = []any{
	(*CreateLobbyRequest)(nil),   // 0: lobby.CreateLobbyRequest
	(*CreateLobbyResponse)(nil),  // 1: lobby.CreateLobbyResponse
	(*JoinLobbyRequest)(nil),     // 2: lobby.JoinLobbyRequest
	(*JoinLobbyResponse)(nil),    // 3: lobby.JoinLobbyResponse
	(*LeaveMyLobbyRequest)(nil),  // 4: lobby.LeaveMyLobbyRequest
	(*LeaveMyLobbyResponse)(nil), // 5: lobby.LeaveMyLobbyResponse
	(*GetLobbiesRequest)(nil),    // 6: lobby.GetLobbiesRequest
	(*GetLobbiesResponse)(nil),   // 7: lobby.GetLobbiesResponse
	(*CloseLobbyRequest)(nil),    // 8: lobby.CloseLobbyRequest
	(*CloseLobbyResponse)(nil),   // 9: lobby.CloseLobbyResponse
	(*LobbySettings)(nil),        // 10: lobby.LobbySettings
	(*Lobby)(nil),                // 11: lobby.Lobby
}
var file_lobby_lobby_controller_proto_depIdxs = []int32{
	10, // 0: lobby.CreateLobbyRequest.lobbySettings:type_name -> lobby.LobbySettings
	11, // 1: lobby.CreateLobbyResponse.lobby:type_name -> lobby.Lobby
	11, // 2: lobby.JoinLobbyResponse.lobby:type_name -> lobby.Lobby
	11, // 3: lobby.GetLobbiesResponse.items:type_name -> lobby.Lobby
	0,  // 4: lobby.LobbyController.CreateLobby:input_type -> lobby.CreateLobbyRequest
	2,  // 5: lobby.LobbyController.JoinLobby:input_type -> lobby.JoinLobbyRequest
	4,  // 6: lobby.LobbyController.LeaveMyLobby:input_type -> lobby.LeaveMyLobbyRequest
	6,  // 7: lobby.LobbyController.GetLobbies:input_type -> lobby.GetLobbiesRequest
	8,  // 8: lobby.LobbyController.CloseMyLobby:input_type -> lobby.CloseLobbyRequest
	1,  // 9: lobby.LobbyController.CreateLobby:output_type -> lobby.CreateLobbyResponse
	3,  // 10: lobby.LobbyController.JoinLobby:output_type -> lobby.JoinLobbyResponse
	5,  // 11: lobby.LobbyController.LeaveMyLobby:output_type -> lobby.LeaveMyLobbyResponse
	7,  // 12: lobby.LobbyController.GetLobbies:output_type -> lobby.GetLobbiesResponse
	9,  // 13: lobby.LobbyController.CloseMyLobby:output_type -> lobby.CloseLobbyResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_lobby_lobby_controller_proto_init() }
func file_lobby_lobby_controller_proto_init() {
	if File_lobby_lobby_controller_proto != nil {
		return
	}
	file_lobby_lobby_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lobby_lobby_controller_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lobby_lobby_controller_proto_goTypes,
		DependencyIndexes: file_lobby_lobby_controller_proto_depIdxs,
		MessageInfos:      file_lobby_lobby_controller_proto_msgTypes,
	}.Build()
	File_lobby_lobby_controller_proto = out.File
	file_lobby_lobby_controller_proto_rawDesc = nil
	file_lobby_lobby_controller_proto_goTypes = nil
	file_lobby_lobby_controller_proto_depIdxs = nil
}
