// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.6
// source: game/game-controller.proto

package game

import (
	math "github.com/DaikoneKisu/recycle-it/server/internal/protos/math"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata: auth-token
type StartGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_game_game_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_game_game_controller_proto_rawDescGZIP(), []int{0}
}

type StartGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStage              *GameStage `protobuf:"bytes,1,opt,name=gameStage,proto3" json:"gameStage,omitempty"`
	TimeRemainingInSeconds int32      `protobuf:"varint,2,opt,name=timeRemainingInSeconds,proto3" json:"timeRemainingInSeconds,omitempty"`
	HasGameEnded           bool       `protobuf:"varint,3,opt,name=hasGameEnded,proto3" json:"hasGameEnded,omitempty"`
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_game_game_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_game_game_controller_proto_rawDescGZIP(), []int{1}
}

func (x *StartGameResponse) GetGameStage() *GameStage {
	if x != nil {
		return x.GameStage
	}
	return nil
}

func (x *StartGameResponse) GetTimeRemainingInSeconds() int32 {
	if x != nil {
		return x.TimeRemainingInSeconds
	}
	return 0
}

func (x *StartGameResponse) GetHasGameEnded() bool {
	if x != nil {
		return x.HasGameEnded
	}
	return false
}

// metadata: auth-token
type JoinGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	mi := &file_game_game_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_game_game_controller_proto_rawDescGZIP(), []int{2}
}

type JoinGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStage              *GameStage `protobuf:"bytes,1,opt,name=gameStage,proto3" json:"gameStage,omitempty"`
	TimeRemainingInSeconds int32      `protobuf:"varint,2,opt,name=timeRemainingInSeconds,proto3" json:"timeRemainingInSeconds,omitempty"`
	HasGameEnded           bool       `protobuf:"varint,3,opt,name=hasGameEnded,proto3" json:"hasGameEnded,omitempty"`
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	mi := &file_game_game_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_game_game_controller_proto_rawDescGZIP(), []int{3}
}

func (x *JoinGameResponse) GetGameStage() *GameStage {
	if x != nil {
		return x.GameStage
	}
	return nil
}

func (x *JoinGameResponse) GetTimeRemainingInSeconds() int32 {
	if x != nil {
		return x.TimeRemainingInSeconds
	}
	return 0
}

func (x *JoinGameResponse) GetHasGameEnded() bool {
	if x != nil {
		return x.HasGameEnded
	}
	return false
}

// metadata: auth-token
type MoveMyTruckToRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewLocation *math.Point `protobuf:"bytes,1,opt,name=newLocation,proto3" json:"newLocation,omitempty"`
}

func (x *MoveMyTruckToRequest) Reset() {
	*x = MoveMyTruckToRequest{}
	mi := &file_game_game_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveMyTruckToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveMyTruckToRequest) ProtoMessage() {}

func (x *MoveMyTruckToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveMyTruckToRequest.ProtoReflect.Descriptor instead.
func (*MoveMyTruckToRequest) Descriptor() ([]byte, []int) {
	return file_game_game_controller_proto_rawDescGZIP(), []int{4}
}

func (x *MoveMyTruckToRequest) GetNewLocation() *math.Point {
	if x != nil {
		return x.NewLocation
	}
	return nil
}

type MoveMyTruckToResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveMyTruckToResponse) Reset() {
	*x = MoveMyTruckToResponse{}
	mi := &file_game_game_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveMyTruckToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveMyTruckToResponse) ProtoMessage() {}

func (x *MoveMyTruckToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveMyTruckToResponse.ProtoReflect.Descriptor instead.
func (*MoveMyTruckToResponse) Descriptor() ([]byte, []int) {
	return file_game_game_controller_proto_rawDescGZIP(), []int{5}
}

// metadata: auth-token
type CollectGarbageWithMyTruckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CollectGarbageWithMyTruckRequest) Reset() {
	*x = CollectGarbageWithMyTruckRequest{}
	mi := &file_game_game_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectGarbageWithMyTruckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectGarbageWithMyTruckRequest) ProtoMessage() {}

func (x *CollectGarbageWithMyTruckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectGarbageWithMyTruckRequest.ProtoReflect.Descriptor instead.
func (*CollectGarbageWithMyTruckRequest) Descriptor() ([]byte, []int) {
	return file_game_game_controller_proto_rawDescGZIP(), []int{6}
}

type CollectGarbageWithMyTruckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CollectGarbageWithMyTruckResponse) Reset() {
	*x = CollectGarbageWithMyTruckResponse{}
	mi := &file_game_game_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectGarbageWithMyTruckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectGarbageWithMyTruckResponse) ProtoMessage() {}

func (x *CollectGarbageWithMyTruckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectGarbageWithMyTruckResponse.ProtoReflect.Descriptor instead.
func (*CollectGarbageWithMyTruckResponse) Descriptor() ([]byte, []int) {
	return file_game_game_controller_proto_rawDescGZIP(), []int{7}
}

// metadata: auth-token
type DepositGarbageFromMyTruckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DepositGarbageFromMyTruckRequest) Reset() {
	*x = DepositGarbageFromMyTruckRequest{}
	mi := &file_game_game_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositGarbageFromMyTruckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositGarbageFromMyTruckRequest) ProtoMessage() {}

func (x *DepositGarbageFromMyTruckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositGarbageFromMyTruckRequest.ProtoReflect.Descriptor instead.
func (*DepositGarbageFromMyTruckRequest) Descriptor() ([]byte, []int) {
	return file_game_game_controller_proto_rawDescGZIP(), []int{8}
}

type DepositGarbageFromMyTruckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DepositGarbageFromMyTruckResponse) Reset() {
	*x = DepositGarbageFromMyTruckResponse{}
	mi := &file_game_game_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositGarbageFromMyTruckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositGarbageFromMyTruckResponse) ProtoMessage() {}

func (x *DepositGarbageFromMyTruckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositGarbageFromMyTruckResponse.ProtoReflect.Descriptor instead.
func (*DepositGarbageFromMyTruckResponse) Descriptor() ([]byte, []int) {
	return file_game_game_controller_proto_rawDescGZIP(), []int{9}
}

var File_game_game_controller_proto protoreflect.FileDescriptor

var file_game_game_controller_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61,
	0x6d, 0x65, 0x1a, 0x15, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x6d, 0x61, 0x74, 0x68, 0x2f,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x12, 0x0a, 0x10, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x9e, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x16, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x16, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x22, 0x0a, 0x0c,
	0x68, 0x61, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x68, 0x61, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x65, 0x64,
	0x22, 0x11, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x9d, 0x01, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x09, 0x67, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x16, 0x74, 0x69, 0x6d, 0x65, 0x52,
	0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x16, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12,
	0x22, 0x0a, 0x0c, 0x68, 0x61, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x68, 0x61, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e,
	0x64, 0x65, 0x64, 0x22, 0x45, 0x0a, 0x14, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x79, 0x54, 0x72, 0x75,
	0x63, 0x6b, 0x54, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x0b, 0x6e,
	0x65, 0x77, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0b, 0x6e,
	0x65, 0x77, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x17, 0x0a, 0x15, 0x4d, 0x6f,
	0x76, 0x65, 0x4d, 0x79, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x20, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x47, 0x61,
	0x72, 0x62, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x79, 0x54, 0x72, 0x75, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x21, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x47, 0x61, 0x72, 0x62, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x79, 0x54,
	0x72, 0x75, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x20,
	0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x47, 0x61, 0x72, 0x62, 0x61, 0x67, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x4d, 0x79, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x23, 0x0a, 0x21, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x47, 0x61, 0x72, 0x62, 0x61,
	0x67, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x79, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb3, 0x03, 0x0a, 0x0e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x3b, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e,
	0x47, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x48, 0x0a, 0x0d, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x79, 0x54,
	0x72, 0x75, 0x63, 0x6b, 0x54, 0x6f, 0x12, 0x1a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x6f,
	0x76, 0x65, 0x4d, 0x79, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x54, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x79,
	0x54, 0x72, 0x75, 0x63, 0x6b, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x6c, 0x0a, 0x19, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x47, 0x61, 0x72, 0x62, 0x61, 0x67,
	0x65, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x79, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x12, 0x26, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x47, 0x61, 0x72, 0x62, 0x61,
	0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x79, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x47, 0x61, 0x72, 0x62, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x79,
	0x54, 0x72, 0x75, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6c, 0x0a,
	0x19, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x47, 0x61, 0x72, 0x62, 0x61, 0x67, 0x65, 0x46,
	0x72, 0x6f, 0x6d, 0x4d, 0x79, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x12, 0x26, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x47, 0x61, 0x72, 0x62, 0x61, 0x67, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x79, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x47, 0x61, 0x72, 0x62, 0x61, 0x67, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x79, 0x54, 0x72,
	0x75, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3f, 0x5a, 0x3d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x69, 0x6b, 0x6f, 0x6e,
	0x65, 0x4b, 0x69, 0x73, 0x75, 0x2f, 0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2d, 0x69, 0x74,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_game_controller_proto_rawDescOnce sync.Once
	file_game_game_controller_proto_rawDescData = file_game_game_controller_proto_rawDesc
)

func file_game_game_controller_proto_rawDescGZIP() []byte {
	file_game_game_controller_proto_rawDescOnce.Do(func() {
		file_game_game_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_game_controller_proto_rawDescData)
	})
	return file_game_game_controller_proto_rawDescData
}

var file_game_game_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_game_game_controller_proto_goTypes = []any{
	(*StartGameRequest)(nil),                  // 0: game.StartGameRequest
	(*StartGameResponse)(nil),                 // 1: game.StartGameResponse
	(*JoinGameRequest)(nil),                   // 2: game.JoinGameRequest
	(*JoinGameResponse)(nil),                  // 3: game.JoinGameResponse
	(*MoveMyTruckToRequest)(nil),              // 4: game.MoveMyTruckToRequest
	(*MoveMyTruckToResponse)(nil),             // 5: game.MoveMyTruckToResponse
	(*CollectGarbageWithMyTruckRequest)(nil),  // 6: game.CollectGarbageWithMyTruckRequest
	(*CollectGarbageWithMyTruckResponse)(nil), // 7: game.CollectGarbageWithMyTruckResponse
	(*DepositGarbageFromMyTruckRequest)(nil),  // 8: game.DepositGarbageFromMyTruckRequest
	(*DepositGarbageFromMyTruckResponse)(nil), // 9: game.DepositGarbageFromMyTruckResponse
	(*GameStage)(nil),                         // 10: game.GameStage
	(*math.Point)(nil),                        // 11: math.Point
}
var file_game_game_controller_proto_depIdxs = []int32{
	10, // 0: game.StartGameResponse.gameStage:type_name -> game.GameStage
	10, // 1: game.JoinGameResponse.gameStage:type_name -> game.GameStage
	11, // 2: game.MoveMyTruckToRequest.newLocation:type_name -> math.Point
	0,  // 3: game.GameController.StartGame:input_type -> game.StartGameRequest
	2,  // 4: game.GameController.JoinGame:input_type -> game.JoinGameRequest
	4,  // 5: game.GameController.MoveMyTruckTo:input_type -> game.MoveMyTruckToRequest
	6,  // 6: game.GameController.CollectGarbageWithMyTruck:input_type -> game.CollectGarbageWithMyTruckRequest
	8,  // 7: game.GameController.DepositGarbageFromMyTruck:input_type -> game.DepositGarbageFromMyTruckRequest
	1,  // 8: game.GameController.StartGame:output_type -> game.StartGameResponse
	3,  // 9: game.GameController.JoinGame:output_type -> game.JoinGameResponse
	5,  // 10: game.GameController.MoveMyTruckTo:output_type -> game.MoveMyTruckToResponse
	7,  // 11: game.GameController.CollectGarbageWithMyTruck:output_type -> game.CollectGarbageWithMyTruckResponse
	9,  // 12: game.GameController.DepositGarbageFromMyTruck:output_type -> game.DepositGarbageFromMyTruckResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_game_game_controller_proto_init() }
func file_game_game_controller_proto_init() {
	if File_game_game_controller_proto != nil {
		return
	}
	file_game_game_stage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_game_controller_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_game_controller_proto_goTypes,
		DependencyIndexes: file_game_game_controller_proto_depIdxs,
		MessageInfos:      file_game_game_controller_proto_msgTypes,
	}.Build()
	File_game_game_controller_proto = out.File
	file_game_game_controller_proto_rawDesc = nil
	file_game_game_controller_proto_goTypes = nil
	file_game_game_controller_proto_depIdxs = nil
}
