// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.6
// source: game/garbage.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Garbage int32

const (
	Garbage_GARBAGE_UNKNOWN Garbage = 0
	Garbage_GARBAGE_PLASTIC Garbage = 1
	Garbage_GARBAGE_GLASS   Garbage = 2
	Garbage_GARBAGE_PAPER   Garbage = 3
	Garbage_GARBAGE_ORGANIC Garbage = 4
	Garbage_GARBAGE_METAL   Garbage = 5
)

// Enum value maps for Garbage.
var (
	Garbage_name = map[int32]string{
		0: "GARBAGE_UNKNOWN",
		1: "GARBAGE_PLASTIC",
		2: "GARBAGE_GLASS",
		3: "GARBAGE_PAPER",
		4: "GARBAGE_ORGANIC",
		5: "GARBAGE_METAL",
	}
	Garbage_value = map[string]int32{
		"GARBAGE_UNKNOWN": 0,
		"GARBAGE_PLASTIC": 1,
		"GARBAGE_GLASS":   2,
		"GARBAGE_PAPER":   3,
		"GARBAGE_ORGANIC": 4,
		"GARBAGE_METAL":   5,
	}
)

func (x Garbage) Enum() *Garbage {
	p := new(Garbage)
	*p = x
	return p
}

func (x Garbage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Garbage) Descriptor() protoreflect.EnumDescriptor {
	return file_game_garbage_proto_enumTypes[0].Descriptor()
}

func (Garbage) Type() protoreflect.EnumType {
	return &file_game_garbage_proto_enumTypes[0]
}

func (x Garbage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Garbage.Descriptor instead.
func (Garbage) EnumDescriptor() ([]byte, []int) {
	return file_game_garbage_proto_rawDescGZIP(), []int{0}
}

var File_game_garbage_proto protoreflect.FileDescriptor

var file_game_garbage_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x67, 0x61, 0x72, 0x62, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x2a, 0x81, 0x01, 0x0a, 0x07, 0x47,
	0x61, 0x72, 0x62, 0x61, 0x67, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x47, 0x41, 0x52, 0x42, 0x41, 0x47,
	0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x47,
	0x41, 0x52, 0x42, 0x41, 0x47, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x53, 0x54, 0x49, 0x43, 0x10, 0x01,
	0x12, 0x11, 0x0a, 0x0d, 0x47, 0x41, 0x52, 0x42, 0x41, 0x47, 0x45, 0x5f, 0x47, 0x4c, 0x41, 0x53,
	0x53, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x47, 0x41, 0x52, 0x42, 0x41, 0x47, 0x45, 0x5f, 0x50,
	0x41, 0x50, 0x45, 0x52, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x47, 0x41, 0x52, 0x42, 0x41, 0x47,
	0x45, 0x5f, 0x4f, 0x52, 0x47, 0x41, 0x4e, 0x49, 0x43, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x47,
	0x41, 0x52, 0x42, 0x41, 0x47, 0x45, 0x5f, 0x4d, 0x45, 0x54, 0x41, 0x4c, 0x10, 0x05, 0x42, 0x3f,
	0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x69,
	0x6b, 0x6f, 0x6e, 0x65, 0x4b, 0x69, 0x73, 0x75, 0x2f, 0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65,
	0x2d, 0x69, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_garbage_proto_rawDescOnce sync.Once
	file_game_garbage_proto_rawDescData = file_game_garbage_proto_rawDesc
)

func file_game_garbage_proto_rawDescGZIP() []byte {
	file_game_garbage_proto_rawDescOnce.Do(func() {
		file_game_garbage_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_garbage_proto_rawDescData)
	})
	return file_game_garbage_proto_rawDescData
}

var file_game_garbage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_garbage_proto_goTypes = []any{
	(Garbage)(0), // 0: game.Garbage
}
var file_game_garbage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_garbage_proto_init() }
func file_game_garbage_proto_init() {
	if File_game_garbage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_garbage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_garbage_proto_goTypes,
		DependencyIndexes: file_game_garbage_proto_depIdxs,
		EnumInfos:         file_game_garbage_proto_enumTypes,
	}.Build()
	File_game_garbage_proto = out.File
	file_game_garbage_proto_rawDesc = nil
	file_game_garbage_proto_goTypes = nil
	file_game_garbage_proto_depIdxs = nil
}
